[build-system]
requires = ["setuptools<68", "setuptools_scm[toml]<8"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37']

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
