[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py39']

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
